const GET_APT_SUCCESS = 'GET_APT_SUCCESS';
const GET_APT_FAIL = 'GET_APT_SUCCESS';
const MAKE_APT_SUCCESS = 'MAKE_APT_SUCCESS';
const MAKE_APT_FAIL = 'MAKE_APT_SUCCESS';
const DELL_SUCCESS = 'DELL_SUCCESS';
const DEL_FROM_REDUX = 'DEL_FROM_REDUX';
const NEW_APPOINTMENT = 'NEW_APPOINTMENT';
export {
  GET_APT_SUCCESS,
  GET_APT_FAIL,
  MAKE_APT_SUCCESS,
  MAKE_APT_FAIL,
  DELL_SUCCESS,
  DEL_FROM_REDUX,
  NEW_APPOINTMENT,
};
