const GET_APT_SUCCESS = 'GET_APT_SUCCESS';
const GET_APT_FAIL = 'GET_APT_SUCCESS';
const MAKE_APT_SUCCESS = 'MAKE_APT_SUCCESS';
const MAKE_APT_FAIL = 'MAKE_APT_SUCCESS';
const DELET_APT = 'DELET_APT';

export {
  GET_APT_SUCCESS, GET_APT_FAIL, MAKE_APT_SUCCESS, MAKE_APT_FAIL, DELET_APT,
};
