const DOCTORS_SUCCESS = 'DOCTORS_SUCCESS';
const DOCTORS_FAILURE = 'DOCTORS_FAILURE';
const SELECTED_DOCTOR = 'SELECTED_DOCTOR';
const INCREMENT = 'INCREMENT';
const DECREMENT = 'DECREMENT';
const FILTER = 'FILTER';
const SET_INDEX = 'SET_INDEX';
const ZERO_INDEX = 'ZERO_INDEX';
export {
  DOCTORS_SUCCESS,
  DOCTORS_FAILURE,
  SELECTED_DOCTOR,
  FILTER,
  INCREMENT,
  DECREMENT,
  SET_INDEX,
  ZERO_INDEX,
};
