const DOCTORS_SUCCESS = 'DOCTORS_SUCCESS';
const DOCTORS_FAILURE = 'DOCTORS_FAILURE';
const SELECTED_DOCTOR = 'SELECTED_DOCTOR';
const FILTER = 'FILTER';
export {
  DOCTORS_SUCCESS, DOCTORS_FAILURE, SELECTED_DOCTOR, FILTER,
};
