const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
const REGISTER_FAILURE = 'REGISTER_FAILURE';
const CLEAR_ERRORS = 'CLEAR_ERRORS';
const NAVSWITCH = 'NAVSWITCH';
const REDIRECT = 'REDIRECT';
const CLEAR_REDIRECT = 'CLEAR_REDIRECT';
export {
  REGISTRATION_SUCCESS,
  REGISTER_FAILURE,
  CLEAR_ERRORS,
  NAVSWITCH,
  REDIRECT,
  CLEAR_REDIRECT,
};
