const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
const REGISTER_FAILURE = 'REGISTER_FAILURE';
const CLEAR_ERRORS = 'CLEAR_ERRORS';
export {
  REGISTRATION_SUCCESS, REGISTER_FAILURE, CLEAR_ERRORS,
};
